//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VSFilter.rc
//
#define IDS_PROJNAME                    100
#define IDD_DVSPATHSPAGE                101
#define IDS_PROJNAME2                   102
#define IDS_DIVX_WARNING                103
#define IDD_DVSABOUTPAGE                104
#define IDS_R_TEXT                      105
#define IDS_R_VOBSUB                    106
#define IDS_R_DEFTEXTPATHES             107
#define IDS_R_PREFLANGS                 108
#define IDS_RG_SAVEFULLPATH             109
#define IDS_RG_EXTPIC                   110
#define IDS_RG_MOD32FIX                 111
#define IDS_RG_LOADLEVEL                112
#define IDS_RG_INSTANTUPDATE            113
#define IDS_RG_FLIPPICTURE              114
#define IDS_RG_HIDE                     115
#define IDS_RG_NOYUY2COLORS             116
#define IDS_RG_SHOWOSDSTATS             118
#define IDS_RG_SEENDIVXWARNING          119
#define IDS_RG_RESX2                    120
#define IDS_RG_RESX2MINW                121
#define IDS_RG_RESX2MINH                122
#define IDS_RTM_MEDIAFPS                123
#define IDS_RT_SHADOW                   124
#define IDS_RT_OUTLINE                  125
#define IDS_RT_LOGFONT                  126
#define IDS_RT_COLOR                    127
#define IDS_RT_OVERRIDEPLACEMENT        128
#define IDS_RT_XPERC                    129
#define IDS_RT_YPERC                    130
#define IDS_RV_BUFFER                   131
#define IDS_RP_PATH                     132
#define IDS_RL_LANG                     133
#define IDS_M_SHOWSUBTITLES             134
#define IDS_M_HIDESUBTITLES             135
#define IDS_M_ORIGINALPICTURE           136
#define IDS_M_FLIPPEDPICTURE            137
#define IDS_RV_POLYGONIZE               138
#define IDS_RG_EXTERNALLOAD             139
#define IDS_RG_WEBLOAD                  140
#define IDS_RG_EMBEDDEDLOAD             141
#define IDS_URL_HOMEPAGE                142
#define IDS_URL_EMAIL                   143
#define IDS_R_TIMING                    144
#define IDS_RTM_SUBTITLEDELAY           145
#define IDS_RTM_SUBTITLESPEEDMUL        146
#define IDS_RT_ADVANCEDRENDERER         147
#define IDS_RV_ONLYSHOWFORCEDSUBS       148
#define IDS_ORGHEIGHT                   149
#define IDS_RG_VMRZOOMENABLED           150
#define IDS_RTM_SUBTITLESPEEDDIV        151
#define IDS_RG_COLORFORMATS             152
#define IDS_EXTTO169                    153
#define IDS_RG_FORCERGB                 154
#define IDS_RG_ENABLEZPICON             155
#define IDS_RG_FLIPSUBTITLES            156
#define IDS_RTM_MEDIAFPSENABLED         157
#define IDS_RG_DISABLERELOADER          158
#define IDS_EXTTO43                     159
#define IDS_CROPTO169                   160
#define IDS_CROPTO43                    161
#define IDS_ORGRES                      162
#define IDS_DBLRES                      163
#define IDS_DBLRESIF                    164
#define IDS_DONOTLOAD                   165
#define IDS_LOADWHENNEEDED              166
#define IDS_ALWAYSLOAD                  167
#define IDS_EXTTO576                    168
#define IDS_EXTTO480                    169
#define IDS_RT_AUTOPARCOMPENSATION      170
#define IDS_RT_PAR_DISABLED             171
#define IDS_RT_PAR_UPSCALE              172
#define IDS_RT_PAR_DOWNSCALE            173
#define IDS_RT_PAR_ACCURATE_SIZE        174
#define IDS_RG_SUBPICTTOBUFFER          175
#define IDS_RG_ANIMWHENBUFFERING        176
#define IDS_RG_ALLOW_DROPPING_SUBPIC    177
#define IDC_FILENAME                    200
#define IDD_DVSMAINPAGE                 201
#define IDC_OPEN                        202
#define IDC_HOMEPAGEBTN                 203
#define IDD_DVSZOOMPAGE                 204
#define IDC_FLIP                        205
#define IDC_HIDE                        206
#define IDC_FLIPSUB                     207
#define IDC_CACHESUB                    208
#define IDC_ONLYSHOWFORCEDSUBS          209
#define IDC_POLYGONIZE                  210
#define IDC_FONT                        211
#define IDC_BUGREPORTBTN                212
#define IDC_CONFIGDLG                   213
#define IDC_SHADOW                      214
#define IDI_ICON1                       215
#define IDC_LANGCOMBO                   216
#define IDD_DVSCOLORPAGE                217
#define IDC_OUTLINE                     220
#define IDD_DVSGENERALPAGE              221
#define IDC_MOD32FIX                    222
#define IDD_DVSTIMINGPAGE               223
#define IDD_DVSMISCPAGE                 224
#define IDC_PREBUFFERING                225
#define IDS_R_GENERAL                   226
#define IDC_EMBLOAD                     227
#define IDS_RT_STYLE                    228
#define IDC_SHOWOSDSTATS                229
#define IDC_OVERRIDEPLACEMENT           230
#define IDC_ANIMWHENBUFFERING           231
#define IDC_CHECK_ALLOW_DROPPING_SUBPIC 322
#define IDC_EDIT1                       233
#define IDC_EDIT2                       234
#define IDC_EDIT7                       235
#define IDC_AUTORELOAD                  236
#define IDD_TEXTSUBOPENTEMPLATE         237
#define IDC_SPIN1                       238
#define IDC_SPIN2                       239
#define IDC_SPIN7                       240
#define IDC_MODFPS                      241
#define IDC_EDIT8                       242
#define IDC_ADVANCEDRENDERER            243
#define IDC_SPIN8                       244
#define IDC_EXTLOAD                     245
#define IDC_WEBLOAD                     246
#define IDC_EDIT3                       247
#define IDC_SPIN3                       248
#define IDC_EDIT4                       249
#define IDD_STYLEDIALOG                 250
#define IDC_SPIN4                       251
#define IDC_EDIT5                       252
#define IDC_SPIN5                       253
#define IDC_EDIT6                       254
#define IDC_SPIN6                       255
#define IDC_EDIT9                       256
#define IDC_SPIN9                       257
#define IDC_PREFLIST                    258
#define IDC_DYNCHGLIST                  259
#define IDC_COLORUP                     260
#define IDC_COLORDOWN                   261
#define IDC_COLORCHANGE                 262
#define IDC_DYNCHGWARNING               263
#define IDC_DYNCHGWARNING2              264
#define IDC_FORCERGBCHK                 265
#define IDC_RESX2COMBO                  290
#define IDC_VEREXTCOMBO                 291
#define IDC_LOADCOMBO                   292
#define IDC_FPS                         300
#define IDC_SAVEFULLPATH                301
#define IDC_INSTANTUPDATE               302
#define IDC_PATHLIST                    303
#define IDC_ADD                         304
#define IDC_REMOVE                      305
#define IDC_BROWSE                      310
#define IDC_PATHEDIT                    311
#define IDC_COMBO1                      312
#define IDC_PARCOMBO                    313
#define IDC_VERSION                     314
#define IDC_SLIDER2                     1000
#define IDC_SLIDER3                     1001
#define IDC_RADIO1                      1002
#define IDC_RADIO2                      1003
#define IDC_CHECK1                      1004
#define IDC_BUTTON1                     1005
#define IDC_EDIT10                      1006
#define IDC_RADIO3                      1007
#define IDC_RADIO4                      1008
#define IDC_RADIO5                      1009
#define IDC_RADIO6                      1010
#define IDC_SLIDER5                     1011
#define IDC_SLIDER6                     1012
#define IDC_EDIT11                      1014
#define IDC_SPIN10                      1015
#define IDC_RADIO7                      1016
#define IDC_RADIO8                      1017
#define IDC_RADIO9                      1018
#define IDC_RADIO10                     1019
#define IDC_RADIO11                     1020
#define IDC_COLORPRI                    1021
#define IDC_COLORSEC                    1022
#define IDC_COLOROUTL                   1023
#define IDC_COLORSHAD                   1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32770
#define _APS_NEXT_CONTROL_VALUE         316
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
