//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mpciconlib.rc
//
#define IDI_DEFAULT_ICON		0
#define IDI_DEFAULT_VIDEO_ICON	1
#define IDI_DEFAULT_AUDIO_ICON	2
#define IDI_3G2_ICON			3
#define IDI_3GP_ICON			4
#define IDI_3GP2_ICON			5
#define IDI_3GPP_ICON			6
#define IDI_AAC_ICON			7
#define IDI_AC3_ICON			8
#define IDI_AIF_ICON			9
#define IDI_AIFC_ICON			10
#define IDI_AIFF_ICON			11
#define IDI_ALAC_ICON			12
#define IDI_AMR_ICON			13
#define IDI_AMV_ICON			14
#define IDI_AOB_ICON			15
#define IDI_APE_ICON			16
#define IDI_APL_ICON			17
#define IDI_ASF_ICON			18
#define IDI_AU_ICON				19
#define IDI_AVI_ICON			20
#define IDI_BIK_ICON			21
#define IDI_CDA_ICON			22
#define IDI_ICON_23				23
#define IDI_DIVX_ICON			24
#define IDI_DSA_ICON			25
#define IDI_DSM_ICON			26
#define IDI_DSS_ICON			27
#define IDI_DSV_ICON			28
#define IDI_DTS_ICON			29
#define IDI_EVO_ICON			30
#define IDI_F4V_ICON			31
#define IDI_FLAC_ICON			32
#define IDI_FLC_ICON			33
#define IDI_FLI_ICON			34
#define IDI_FLIC_ICON			35
#define IDI_FLV_ICON			36
#define IDI_HDMOV_ICON			37
#define IDI_IFO_ICON			38
#define IDI_IVF_ICON			39
#define IDI_M1A_ICON			40
#define IDI_M1V_ICON			41
#define IDI_M2A_ICON			42
#define IDI_M2P_ICON			43
#define IDI_M2T_ICON			44
#define IDI_M2TS_ICON			45
#define IDI_M2V_ICON			46
#define IDI_M4A_ICON			47
#define IDI_M4B_ICON			48
#define IDI_M4V_ICON			49
#define IDI_MID_ICON			50
#define IDI_MIDI_ICON			51
#define IDI_MKA_ICON			52
#define IDI_MKV_ICON			53
#define IDI_MLP_ICON			54
#define IDI_MOV_ICON			55
#define IDI_MP2_ICON			56
#define IDI_MP2V_ICON			57
#define IDI_MP3_ICON			58
#define IDI_MP4_ICON			59
#define IDI_MP4V_ICON			60
#define IDI_MPA_ICON			61
#define IDI_MPC_ICON			62
#define IDI_MPE_ICON			63
#define IDI_MPEG_ICON			64
#define IDI_MPG_ICON			65
#define IDI_MPV2_ICON			66
#define IDI_MPV4_ICON			67
#define IDI_MTS_ICON			68
#define IDI_OFR_ICON			69
#define IDI_OFS_ICON			70
#define IDI_OGA_ICON			71
#define IDI_OGG_ICON			72
#define IDI_OGM_ICON			73
#define IDI_OGV_ICON			74
#define IDI_PLAYLIST_ICON		75
#define IDI_PVA_ICON			76
#define IDI_RA_ICON				77
#define IDI_RAM_ICON			78
#define IDI_RATDVD_ICON			79
#define IDI_REC_ICON			80
#define IDI_RM_ICON				81
#define IDI_RMI_ICON			82
#define IDI_RMM_ICON			83
#define IDI_ROQ_ICON			84
#define IDI_RP_ICON				85
#define IDI_RT_ICON				86
#define IDI_ICON_87				87
#define IDI_SMIL_ICON			88
#define IDI_SMK_ICON			89
#define IDI_SND_ICON			90
#define IDI_SWF_ICON			91
#define IDI_TAK_ICON			92
#define IDI_TP_ICON				93
#define IDI_TRP_ICON			94
#define IDI_TS_ICON				95
#define IDI_TTA_ICON			96
#define IDI_VOB_ICON			97
#define IDI_WAV_ICON			98
#define IDI_WEBM_ICON			99
#define IDI_WM_ICON				100
#define IDI_WMA_ICON			101
#define IDI_WMP_ICON			102
#define IDI_WMV_ICON			103
#define IDI_WV_ICON				104
#define IDI_OPUS_ICON			105
#define IDI_NONE				-1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE		107
#define _APS_NEXT_COMMAND_VALUE			40001
#define _APS_NEXT_CONTROL_VALUE			1001
#define _APS_NEXT_SYMED_VALUE			101
#endif
#endif
