/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-n6.1-dev-2279-g5d98259841"
#endif /* AVUTIL_FFVERSION_H */
